//
//  Ingredient.swift
//  LittleLemonDinnerMenu
//
//  Created by Mike on 12/23/22.
//

enum Ingredient: String {
    case spinach = "Spinach"
    case broccoli = "Broccoli"
    case carrot = "Carrot"
    case pasta = "Pasta"
    case tomatoSauce = "Tomato Sauce"
    case mozzarella = "Mozzarella"
    case egg = "Egg"
    case bacon = "Bacon"
    case parmesan = "Parmesan"
    case beef = "Beef"
    case bread = "Bread"
    case tomato = "Tomato"
    case basil = "Basil"
    case eggplant = "Eggplant"
    case arborioRice = "Arborio Rice"
    case saffron = "Saffron"
    case beefBroth = "Beef Broth"
    case cornmeal = "Cornmeal"
    case water = "Water"
    case butter = "Butter"
    case vegetableBroth = "Vegetable Broth"
    case vegetables = "Vegetables"
    case beans = "Beans"
    case vinaigrette = "Vinaigrette"
    case onion = "Onion"
    case cucumber = "Cucumber"
    case mascarpone = "Mascarpone"
    case espresso = "Espresso"
    case cocoa = "Cocoa"
    case ladyfingers = "Ladyfingers"
    case ricotta = "Ricotta"
    case chocolateChips = "Chocolate Chips"
    case pastryCrust = "Pastry Crust"
    case espressoBeans = "Espresso Beans"
    case milk = "Milk"
    case foam = "Foam"
    case carbonatedWater = "Carbonated Water"
    case syrup = "Syrup"
    case vodka = "Vodka"
    case lemonPeel = "Lemon Peel"
    case prosecco = "Prosecco"
    case aperol = "Aperol"
    case sodaWater = "Soda Water"
    case gin = "Gin"
    case vermouth = "Vermouth"
    case campari = "Campari"
    case whiteWine = "White Wine"
    case grapes = "Grapes"
    case cream = "Cream"
    case flavorings = "Flavorings"
    case sugar = "Sugar"
    case vanilla = "Vanilla"
}
